### ISSUE TITLE
note about hidden files and directories

### ISSUE THREAD

**Issue by mcase07** [parunjodhi/mpm#9]
Hey @rudeboybert we're unsure how to resolve this `NOTE`:

`❯ checking for hidden files and directories ... NOTE
  Found the following hidden files and directories:
    data/..rda
  These were most likely included in error. See section ‘Package
  structure’ in the ‘Writing R Extensions’ manual.`

`..rda` seems to have been generated when we loaded one of our csvs in and doesn't contain anything when we try to load it.

**Comment by rudeboybert** [comment]
how about deleting the file? you may need to "show hidden files" in RStudio per these [instructions](https://www.rstudio.com/blog/rstudio-1-2-preview-the-little-things/#:~:text=Click%20More%20on%20the%20Files%20pane%2C%20then%20check%20Show%20Hidden%20Files.) to do that.

**Comment by parunjodhi** [comment]
Thank you Professor! We tried it and it worked!
